// FE-Angular/src/app/app.component.ts
// app.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { HubConnection, HubConnectionBuilder, LogLevel } from '@microsoft/signalr';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit, OnDestroy {
  connectionId: string | undefined;
  conn: HubConnection | undefined;

  ngOnInit(): void {
    this.conn = new HubConnectionBuilder()
      .withUrl('https://localhost:5001/chat')
      .configureLogging(LogLevel.Information)
      .build();

    this.conn.on('ReceiveMessage', (username: string, msg: string, connId: string) => {
      const li = document.createElement('li');
      li.textContent = `${connId}: ${username} says ${msg}`;
      document.getElementById('messagesList')?.appendChild(li);
      console.log(`Message: ${msg}, from ${username}`);
    });

    this.conn.start()
      .then(() => {
        this.conn?.invoke('GetConnectionId').then((id: string) => {
          console.log(id);
          this.connectionId = id;
        });
      })
      .catch(error => console.error('Error establishing connection:', error));
  }

  ngOnDestroy(): void {
    this.conn?.stop();
  }

  sendMessage(event : any): void {
    this.conn?.invoke('SendMessage', event.username, event.message).catch(e => console.error(e));
  }

  sendToUser(event : any): void {
    this.conn?.invoke('SendToUser', event.username, event.receiverId, event.message).catch(e => console.error(e));
  }
}

<!-- app.component.html -->
<div>
  <main>
    <div class="row">
      <div class="col-3">Connection Id</div>
      <div class="col-"><span id="connectionId">{{ connectionId }}</span></div>
    </div>
    <div class="container">
      <div class="row px-5 my-5">
        <div class="col-sm-12">
          <h1 class="font-weight-light">Welcome to the F1 ChatApp</h1>
        </div>
      </div>
      <app-chat-room (sendMessage)="sendMessage($event)" (sendToUser)="sendToUser($event)"></app-chat-room>
    </div>
    <div class="row">
      <div class="col-6">
        <ul id="messagesList"></ul>
      </div>
    </div>
  </main>
</div>

// FE-React/src/App.js
import { Col, Container, Row } from 'react-bootstrap';
import './App.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import WaitingRoom from './components/waitingroom';
import { useEffect, useState } from 'react';
import { HubConnectionBuilder, LogLevel } from '@microsoft/signalr';

function App() {
  const [conn, setConnection] = useState();

  useEffect(() => {
    const connection = new HubConnectionBuilder()
      .withUrl("https://localhost:5001/chat")
      .configureLogging(LogLevel.Information)
      .build();

    connection.on("ReceiveMessage", (username, msg, connId) => {
      const li = document.createElement('li');
      li.textContent = connId + ": " + username + " says " + msg;
      document.getElementById('messagesList').appendChild(li);
      console.log(`Message: ${msg}, from ${username}`);
    });

    connection.start()
      .then(() => {
        connection.invoke("GetConnectionId").then(function (id) {
          console.log(id);
          document.getElementById("connectionId").innerText = id;
        });
      })
      .catch(error => console.error('Error establishing connection:', error));

    setConnection(connection);

    return () => {
      connection.stop();
    };
  }, []);

  const sendMessage = async (username, message) => {
    try {
      await conn.invoke("SendMessage", username, message);
    } catch (e) {
      console.error(e);
    }
  };

  const sendToUser = async (username, message, receiverId) => {
    try {
      await conn.invoke("SendToUser", username, receiverId, message)
    } catch (e) {
      console.error(e);
    }
  }
  
  return (
    <div>
      <main>
        <div className='row'>
          <div className='col-3'>Connection Id</div>
          <div className='col-'><span id='connectionId'></span></div>
        </div>
        <Container>
          <Row className="px-5 my-5">
            <Col sm='12'>
              <h1 className='font-weight-light'>Welcome to the F1 ChatApp</h1>
            </Col>
          </Row>
          <WaitingRoom sendMessage={sendMessage} sendToUser={sendToUser}></WaitingRoom>
        </Container>
        <div className="row">
            <div className="col-6">
                <ul id='messagesList'></ul>
            </div>
        </div>
      </main>
    </div>
  );
}

export default App;
